# hydra:
#   name: regression
#   run:
#     dir: ./${hydra.name}/${model.tag}.${seed}
#   sweep:
#     dir: ${hydra.name}
#     subdir: ${model.tag}.${seed}

model: ${emgn}
enet: ${enet_rff}
n_disp_step: 500 # 200
show_plot: False # True
n_update: 2000
n_inner_update: 1
seed: 0
n_hidden: 128
n_samples: 100
clip_norm: True
lr: 1e-4

enet_basic:
  class: regression.EnergyNetBasic
  tag: enet_basic
  params:
    n_hidden: 128

enet_rff:
  class: regression.EnergyNetRFF
  tag: enet_rff
  params:
    n_hidden: 128
    sigma: 1.
    encoded_size: 128

gd:
  class: regression.UnrollEnergyGD
  tag: gd
  params:
    n_inner_iter: 10
    inner_lr: 1e-2

gn:
  class: regression.UnrollEnergyGN
  tag: gn
  params:
    n_inner_iter: 10
    inner_lr: 1 # Standard GN is 1.0

dcem:
  class: regression.UnrollEnergyCEM
  tag: dcem
  params:
    n_sample: 100
    n_elite: 10
    n_iter: 10
    init_sigma: 1.
    temp: 1.
    normalize: True

emcem:
  class: regression.EnergyModelCEM
  tag: emcem
  params:
    n_sample: 100
    temp: 1.
    min_cov: 1e-3
    max_cov: 10.0
    cem_n_sample: 100
    cem_n_elite: 10
    cem_n_iter: 10
    cem_init_sigma: 7.
    cem_temp: 1.
    cem_normalize: True

emgn:
  class: regression.EnergyModelGN
  tag: emgn
  params:
    n_sample: 100
    temp: 1e9
    n_inner_iter: 10.
    min_cov: 1e-3
    max_cov: 10.0
